# Generated by Django 4.1.7 on 2023-06-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='author',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
