# Generated by Django 4.1.7 on 2023-06-17 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('parent_materials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_materials', to='courses.materials')),
            ],
        ),
        migrations.CreateModel(
            name='reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replied_to', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_forum', to='forums.forum')),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('parent_thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_thread', to='forums.thread')),
            ],
        ),
    ]
